// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace calculador_distancia_euclidiano.Models;

public partial class Context : DbContext
{
    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<PlanoCartesiano> PlanoCartesianos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PlanoCartesiano>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlanoCar__3214EC072B07ED44");

            entity.ToTable("PlanoCartesiano");

            entity.Property(e => e.FechaCalculo).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}